# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b19a79d08576a40e8458e39356959a6d729493eb26c41beb27ed71f64c03d61062314cdbc7a266bfb2858d5ceab17a2f9b1d22d5f29ccc6c77c97f6d923a067

test:
  secret_key_base: f2b5e260eff87be12017480e8c01ba404fd9e335452b1e4842fad70863509305784e0fcac759fb78bc172b2f86e924cb9ec578683c30244fd9f2ccbeab0f1e30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
